src/django_tutorial/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
]

src/django_tutorial/polls/urls.py
from django.urls import path

from . import views

# app_name を追加することで、{% url polls:detail %} のように URL を参照できるようになる
app_name = "polls"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

src/django_tutorial/polls/models.py
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    @admin.display(boolean=True, ordering="pub_date", description="最近の質問かどうか")
    def was_published_recently(self):
        now = timezone.now()
        twenty_four_hours_ago = now - datetime.timedelta(days=1)
        return twenty_four_hours_ago <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

src/django_tutorial/polls/views.py
from django.db.models import F
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    # template_name を指定しない場合は、
    # デフォルトで <app_name>/<model_name>_list.html が使用される
    # 今回はデフォルト名とは異なる templates 名なので、明示的に指定する必要がある
    template_name = "polls/index.html"
    # context_object_name を指定しない場合、
    # デフォルトで <model_name>_list という名称になる
    # デフォルト値とは異なる名前で定義していたので、明示的に指定が必要
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """最新の5件の質問を取得する

        追加要件: 公開日が未来の質問は表示しない
        """
        not_future_questions = Question.objects.filter(pub_date__lte=timezone.now())
        return not_future_questions.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """公開日が未来の質問は表示しない"""
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request: HttpRequest, question_id: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # 以下が主なエラー時
        # 1. POST メソッドでデータが送信されていない
        # 2. 選択肢が選択されていない
        # 3. 存在しない選択肢のIDが送信s慣れた場合 (Question.DoesNotExist)
        return render(
            request,
            "polls/detail.html",
            {"question": question, "error_message": "選択肢が選択されていません"},
        )
    else:
        # F はデータの競合を避けつつ値を更新するために利用する
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # POSTメソッドでデータが更新された場合は、HttpResponseRedirect を返すのが Web のベストプラクティス
        # reverse は URL を「逆引き」するもの
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

src/django_tutorial/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ question.question_text }} - 投票詳細</title>
  </head>
  <body>
    <div class="container">
      <h1>{{ question.question_text }}</h1>

      {% if error_message %}
      <p class="error">{{ error_message }}</p>
      {% endif %}

      <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %} {% for choice in question.choice_set.all %}
        <div class="choice">
          <input
            type="radio"
            name="choice"
            id="choice{{ forloop.counter }}"
            value="{{ choice.id }}"
          />
          <label for="choice{{ forloop.counter }}">
            {{ choice.choice_text }}
          </label>
        </div>
        {% endfor %}
        <input type="submit" value="投票する" />
      </form>

      <p><a href="/polls/">質問一覧に戻る</a></p>
    </div>
  </body>
</html>

src/django_tutorial/polls/templates/polls/index.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'polls/style.css' %}" />
    <title>投票アプリ</title>
  </head>
  <body>
    <div>
      <h1>投票機能ページだよ</h1>
      <p>最新の質問があれば以下に掲載されるよ</p>
      {% if latest_question_list %}
      <ul>
        {% for question in latest_question_list %}
        <li>
          <a href="{% url 'polls:detail' question.id %}">
            {{ question.question_text }}
          </a>
        </li>
        {% endfor %}
      </ul>
      {% else %}
      <p>質問がありません。</p>
      {% endif %}
    </div>
  </body>
</html>

src/django_tutorial/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>投票結果 - {{ question.question_text }}</title>
  </head>
  <body>
    <h1>{{ quetion.question_text }}</h1>
    <ul>
      {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text}} -- {{ choice.votes}} 票</li>
      {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' question.id %}">もう一度投票する</a>
  </body>
</html>